[template]
cargo_generate_version = ">=0.17.4"
ignore = [".git", "assets", "README.md"]

[hooks]
post = ["post-script.rhai"]

[placeholders]
tokio_features = { type = "string", prompt = "Enter Tokio features you wish to use ( e.g., full, rt-multi-thread, io-util):", default = "full" }

[conditional.'tokio_features'.placeholders.multi_choice]
type = "array"
prompt = "Please select one or more, default feature is full:"
choice = ["full", "rt", "rt-multi-thread", "io-util", "io-std", "net", "time", "process", "macros", "sync", "signal", "fs", "test-util", "parking_lot"]
default = ["full"]
