[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2024"
authors = ["{{authors}}"]
resolver = "2"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
tokio = { version = "1", features = ["{{tokio_features}}"] }

[profile.dev]
debug = 2
lto = true
opt-level = "z"